/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ql_nhanvien;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FQL_Giangvien extends javax.swing.JFrame {
    public int ID;
    /**
     * Creates new form QL_Giangvien
     */
    public FQL_Giangvien() {
        initComponents();
        Load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Dangxuat = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Quaylai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        _Hoten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        _Sdt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        _MaGV = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        _Diachi = new javax.swing.JTextArea();
        jLabel45 = new javax.swing.JLabel();
        _Luong = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        _Email = new javax.swing.JTextField();
        _CN = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        cbb_Hang = new javax.swing.JComboBox<>();
        Date_Ngaysinh = new com.toedter.calendar.JDateChooser();
        cbb_Gioitinh = new javax.swing.JComboBox<>();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        _Timkiem = new javax.swing.JTextField();
        cbb_Timkiem = new javax.swing.JComboBox<>();
        btn_Timkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Giangvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thông tin cá nhân");

        jLabel_Dangxuat.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jLabel_Dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Dangxuat.setText("Đăng xuất");
        jLabel_Dangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_DangxuatMouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/re/images/gvien__1_-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel_Quaylai.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jLabel_Quaylai.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Quaylai.setText("Quay lại");
        jLabel_Quaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Quaylai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_QuaylaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Quaylai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/re/images/tải_xuống__2_-removebg-preview.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nhập thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel4.setText("Họ và tên:");

        _Hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _HotenActionPerformed(evt);
            }
        });

        jLabel5.setText("Giới tính:");

        jLabel6.setText("Ngày sinh:");

        jLabel7.setText("Số điện thoại");

        _Sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _SdtActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã giảng viên:");

        jLabel43.setText("Chuyên ngành:");

        jLabel44.setText("Địa chỉ:");

        _Diachi.setColumns(20);
        _Diachi.setRows(5);
        jScrollPane5.setViewportView(_Diachi);

        jLabel45.setText("Lương:");

        jLabel46.setText("Email:");

        _Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _EmailActionPerformed(evt);
            }
        });

        jLabel48.setText("Hạng");

        cbb_Hang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hạng 1", "Hạng 2", "Hạng 3" }));

        cbb_Gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Chưa xác định" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbb_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(20, 20, 20)
                        .addComponent(_CN))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(61, 61, 61)
                                .addComponent(_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_Hoten, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbb_Gioitinh, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Date_Ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(_MaGV)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46)
                                    .addComponent(jLabel44))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(_Sdt)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(_Email))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(_MaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_Gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Date_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(_Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(_CN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel10.setText("Tìm kiếm mã, họ và tên");

        _Timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _TimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(_Timkiem)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(40, 40, 40))
        );

        cbb_Timkiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã giảng viên", "Họ và tên", " " }));

        btn_Timkiem.setText("Tìm kiếm");
        btn_Timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimkiemActionPerformed(evt);
            }
        });

        jTable_Giangvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ và tên", "Giới tính", "Ngày/tháng/năm sinh", "Email", "Số điện thoại", "Địa chỉ", "Chuyên ngành", "Hạng", "Lương"
            }
        ));
        jTable_Giangvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_GiangvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Giangvien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbb_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_DangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DangxuatMouseClicked
        // TODO add your handling code here:
       FQL_Dangnhap dn = new FQL_Dangnhap();
       dn.setLocationRelativeTo(null);
       dn.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel_DangxuatMouseClicked

    private void jLabel_QuaylaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_QuaylaiMouseClicked
        // TODO add your handling code here:
        FQL_Menu mn = new FQL_Menu();
        mn.ID = ID;
        mn.setVisible(true);
        mn.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_QuaylaiMouseClicked

    private void _HotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__HotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__HotenActionPerformed

    private void _SdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__SdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__SdtActionPerformed

    private void _EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__EmailActionPerformed

    private void btn_TimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimkiemActionPerformed
        // TODO add your handling code here:
        /*JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Choose an open file");
        int result = chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        /*if (result == chooser.APPROVE_OPTION) {
            jLabel13.setIcon(new ImageIcon(filename));
        }
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf =new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
*/      Timkiem();
    }//GEN-LAST:event_btn_TimkiemActionPerformed

    private void _TimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__TimkiemActionPerformed
        // TODO add your handling code here:
        Timkiem();
    }//GEN-LAST:event__TimkiemActionPerformed

    private void jTable_GiangvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_GiangvienMouseClicked
        // TODO add your handling code here:
        if(jTable_Giangvien.getSelectedRow() == -1) return;
        int row = jTable_Giangvien.getSelectedRow();
        _MaGV.setText(jTable_Giangvien.getValueAt(row, 0).toString());
        _Hoten.setText(jTable_Giangvien.getValueAt(row, 1).toString());
        cbb_Gioitinh.setSelectedItem(jTable_Giangvien.getValueAt(row,2));
        try {
            int srow = jTable_Giangvien.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)jTable_Giangvien.getValueAt(srow, 3));
            Date_Ngaysinh.setDate(date);
        } catch(Exception ex) {
            JOptionPane.showConfirmDialog(this,"không thể format");
        }
        _Email.setText(jTable_Giangvien.getValueAt(row, 4).toString());
        _Sdt.setText(jTable_Giangvien.getValueAt(row, 5).toString());
        _Diachi.setText(jTable_Giangvien.getValueAt(row, 6).toString());
        _CN.setText(jTable_Giangvien.getValueAt(row, 7).toString());
        cbb_Hang.setSelectedItem(jTable_Giangvien.getValueAt(row,8));
        _Luong.setText(jTable_Giangvien.getValueAt(row, 9).toString());
    }//GEN-LAST:event_jTable_GiangvienMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        if(Check_TT()) {
           Themmoi();
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        if(Check_TT()) {
             Sua();
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
          if(_MaGV.getText().equals("") || _Hoten.getText().equals("") || _Email.getText().equals(ABORT) || _Sdt.getText().equals("") || _Diachi.getText().equals("") || _CN.getText().equals("") || _Luong.getText().equals("") || jTable_Giangvien.getSelectedRow() == -1) {
            JOptionPane.showConfirmDialog(this, "Vui lòng điền đầy đủ thông tin hoặc chọn hàng cần xóa!","Thông báo",JOptionPane.OK_OPTION);
            return;
        } 
        Xoa();
    }//GEN-LAST:event_btn_XoaActionPerformed
// sUA
    private void Sua() {
        String sql = "UPDATE GIANGVIEN SET HOTEN = ? , GIOITINH = ?,NGAYSINH =?,EMAIL =?, SDT = ?, DIACHI =?, CHUYENNGANH = ?,HANG = ?, LUONG = ? WHERE MAGV = ?";
            try {
                Connection conn = QL_Controller.getJDBCConnection();
                PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.setNString(1,_Hoten.getText());
                pstm.setNString(2,cbb_Gioitinh.getSelectedItem().toString());
                try {
                    
                    SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
                    String d = date.format(Date_Ngaysinh.getDate());
                    pstm.setString(3,d);
                } catch(Exception e) {
                    JOptionPane.showConfirmDialog(this, "Loi :" +e.getMessage());
                }
                pstm.setString(4,_Email.getText());
                pstm.setString(5, _Sdt.getText());
                pstm.setNString(6, _Diachi.getText());
                pstm.setNString(7,_CN.getText());
                pstm.setNString(8,cbb_Hang.getSelectedItem().toString());
                pstm.setString(9 , _Luong.getText());
                pstm.setString(10,_MaGV.getText());
                
                if(JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa dữ liệu?","Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                pstm.execute();
                JOptionPane.showConfirmDialog(this,"Sửa thành công","Thông báo",JOptionPane.OK_OPTION);

                } else {
                    return;
                }
                conn.close();
            } catch(SQLException e) {
                JOptionPane.showConfirmDialog(rootPane, "Loi :" + e.getMessage()); 
            }
            Load_table();
            reText();
    }
    // Xoa
    private void Xoa() {
        String sql = "DELETE FROM GIANGVIEN WHERE MAGV  =  '" + _MaGV.getText() + "'";
        if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa thông tin không?","Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
            Connection conn = QL_Controller.getJDBCConnection();
            Statement stm = conn.createStatement();
            stm.execute(sql);
            JOptionPane.showConfirmDialog(this,"Xóa thành công!", "Thông báo",JOptionPane.OK_OPTION);
            conn.close();
            } catch (SQLException e) {
                JOptionPane.showConfirmDialog(this,"Loi :" + e.getMessage());
            }
        } 
        Load_table();
        reText();
    }
// them moi
    private void Themmoi() {
        String sql = "INSERT INTO GIANGVIEN(MAGV,HOTEN,GIOITINH,NGAYSINH,EMAIL,SDT,DIACHI,CHUYENNGANH,HANG,LUONG) VALUES(?,?,?,?,?,?,?,?,?,?)";
            
            try {
                Connection conn = QL_Controller.getJDBCConnection();
                PreparedStatement pstm = conn.prepareStatement(sql);
                
                pstm.setString(1,_MaGV.getText());
                pstm.setNString(2,_Hoten.getText());
                pstm.setNString(3,cbb_Gioitinh.getSelectedItem().toString());
                try {
                    
                    SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
                    String d = date.format(Date_Ngaysinh.getDate());
                    pstm.setString(4,d);
                } catch(Exception e) {
                    JOptionPane.showConfirmDialog(this, "Loi :" +e.getMessage());
                }
                pstm.setNString(5,_Email.getText());
                pstm.setString(6,_Sdt.getText());
                pstm.setNString(7,_Diachi.getText());
                pstm.setNString(8,_CN.getText());
                pstm.setNString(9,cbb_Hang.getSelectedItem().toString());
                pstm.setString(10,_Luong.getText());

                if(JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm dữ liệu?","Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    pstm.executeUpdate();
                    JOptionPane.showConfirmDialog(this,"Thêm thành công","Thông báo",JOptionPane.OK_OPTION);
                } else {
                    return;
                }
                Load_table();
                reText();
                conn.close();
            } catch(SQLException ex) {
                JOptionPane.showConfirmDialog(this, "Lỗi :" + ex.getMessage());
            }
    }
    // Tim kiem
    private void Timkiem() {
        if(cbb_Timkiem.getSelectedIndex() == -1) {
            JOptionPane.showConfirmDialog(this, "Vui lựa chọn trường thông tin dùng để tìm kiếm","Thông báo",JOptionPane.OK_OPTION);
            return;
        }
        if (_Timkiem.getText().equals("")) {
            Load_table();
        } else {
             if(cbb_Timkiem.getSelectedIndex() == 0) {
                String sql = "SELECT * FROM GIANGVIEN WHERE MAGV = '" + _Timkiem.getText()+"'";
                ArrayList<QL_Giangvien> List_Gv = new ArrayList<>();
                DefaultTableModel model = (DefaultTableModel)jTable_Giangvien.getModel();
                model.setRowCount(0);
                try {
                Connection conn = QL_Controller.getJDBCConnection();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                // đọc dữ liệu vào list
                while(rs.next()) {
                    String Magv = rs.getString("MAGV");
                    String Hoten = rs.getNString("HOTEN");
                    String Gioitinh = rs.getNString("GIOITINH");
                    String Ngaysinh = rs.getString("NGAYSINH");
                    String Email = rs.getString("EMAIL");
                    String Sdt = rs.getString("SDT");
                    String Diachi = rs.getNString("DIACHI");
                    String CN = rs.getNString("CHUYENNGANH");
                    String Hang = rs.getNString("HANG");
                    String Luong = rs.getString("LUONG");
                    QL_Giangvien gv = new QL_Giangvien(Magv,Hoten, Gioitinh, Ngaysinh,Email, Sdt,Diachi,CN,Hang,Luong);
                    List_Gv.add(gv);
                    }

                    for(QL_Giangvien _ac : List_Gv) {
                        model.addRow(new Object[] {
                           _ac.getMagv(),_ac.getHoten(),_ac.getGioitinh(),_ac.getNgaysinh(),_ac.getEmail(),_ac.getSdt(),_ac.getDiachi(),_ac.getCN(),_ac.getHang(),_ac.getLuong()
                        });
                    }
                    conn.close();
                } catch(SQLException ex) {
                    JOptionPane.showInputDialog(this,"Lỗi" + ex.getMessage());
            }
        }
       
        }    
    }
    // load table
        private void Load_table() {
            String sql = "SELECT * FROM GIANGVIEN";
            ArrayList<QL_Giangvien> List_Gv = new ArrayList<>();
            DefaultTableModel model = (DefaultTableModel)jTable_Giangvien.getModel();
            model.setRowCount(0);
            try {
                Connection conn = QL_Controller.getJDBCConnection();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                // đọc dữ liệu vào list
                while(rs.next()) {
                    String Magv = rs.getString("MAGV");
                    String Hoten = rs.getNString("HOTEN");
                    String Gioitinh = rs.getNString("GIOITINH");
                    String Ngaysinh = rs.getString("NGAYSINH");
                    String Email = rs.getString("EMAIL");
                    String Sdt = rs.getString("SDT");
                    String Diachi = rs.getNString("DIACHI");
                    String CN = rs.getNString("CHUYENNGANH");
                    String Hang = rs.getNString("HANG");
                    String Luong = rs.getString("LUONG");
                    QL_Giangvien gv = new QL_Giangvien(Magv,Hoten, Gioitinh, Ngaysinh,Email, Sdt,Diachi,CN,Hang,Luong);
                    List_Gv.add(gv);
                }

                for(QL_Giangvien _ac : List_Gv) {
                    model.addRow(new Object[] {
                       _ac.getMagv(),_ac.getHoten(),_ac.getGioitinh(),_ac.getNgaysinh(),_ac.getEmail(),_ac.getSdt(),_ac.getDiachi(),_ac.getCN(),_ac.getHang(),_ac.getLuong()
                    });
                }
                conn.close();
            } catch(SQLException ex) {
                JOptionPane.showInputDialog(this,"Lỗi" + ex.getMessage());
        }
    }
        // kiem tra ky tu dang so
    private Integer Check_Number(String value) {
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            return null;
        }           
    }
    
    private boolean Check_TT() {
        if(_MaGV.getText().equals("") || _Hoten.getText().equals("") || _Email.getText().equals(ABORT) || _Sdt.getText().equals("") || _Diachi.getText().equals("") || _CN.getText().equals("") || _Luong.getText().equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng điền đầy đủ thông tin!","Thông báo",JOptionPane.OK_OPTION);
            return false;
        } 
        if(Check_Number(_Sdt.getText()) == null) {
            JOptionPane.showConfirmDialog(this, "Số điện thoại không bao gồm ký tự chữ cái!!","Thông báo",JOptionPane.OK_OPTION);
            return false;
        }
        if(Check_Number(_Luong.getText()) == null) {
            JOptionPane.showConfirmDialog(this, "Lương không bao gồm ký tự chữ cái!","Thông báo",JOptionPane.OK_OPTION);
            return false;
        }
        return true;
    }
    
    private void reText() {
        _MaGV.setText("");
        _Hoten.setText("");
        cbb_Gioitinh.setSelectedIndex(0);
        _Email.setText("");
        _Sdt.setText("");
        _Diachi.setText("");
        _CN.setText("");
        cbb_Hang.setSelectedIndex(0);
        _Luong.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FQL_Giangvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FQL_Giangvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FQL_Giangvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FQL_Giangvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FQL_Giangvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_Ngaysinh;
    private javax.swing.JTextField _CN;
    private javax.swing.JTextArea _Diachi;
    private javax.swing.JTextField _Email;
    private javax.swing.JTextField _Hoten;
    private javax.swing.JTextField _Luong;
    private javax.swing.JTextField _MaGV;
    private javax.swing.JTextField _Sdt;
    private javax.swing.JTextField _Timkiem;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Timkiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbb_Gioitinh;
    private javax.swing.JComboBox<String> cbb_Hang;
    private javax.swing.JComboBox<String> cbb_Timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Dangxuat;
    private javax.swing.JLabel jLabel_Quaylai;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable_Giangvien;
    // End of variables declaration//GEN-END:variables
}
